[zh-cn]
  title = "MtF.wiki"
  languageName = "简体中文"
  weight = 1
  contentDir = "content/zh-cn"
[zh-cn.params]
  currency = "CNY"

[zh-hant]
  title = "MtF.wiki"
  languageName = "繁體中文"
  weight = 2
  contentDir = "content/zh-hant"
[zh-hant.params]
  currency = "TWD"

[ja]
  title = "MtF.wiki"
  languageName = "日本語"
  weight = 3
  contentDir = "content/ja"
[ja.params]
  currency = "JPY"

[en]
  title = "MtF.wiki"
  languageName = "English"
  weight = 4
  contentDir = "content/en"
[en.params]
  currency = "USD"

[es]
  title = "MtF.wiki"
  languageName = "Español"
  weight = 5
  contentDir = "content/es"
[es.params]
  currency = "EUR"
