# see https://github.com/actions/labeler

Content | 内容:
- changed-files:
  - any-glob-to-any-file: '**/docs/**'

HRT:
- changed-files:
  - any-glob-to-any-file:
    - '**/docs/hrt/**'
    - '**/docs/medicine/**'

SRS:
- changed-files:
  - any-glob-to-any-file: '**/docs/srs/**'

FFS:
- changed-files:
  - any-glob-to-any-file: '**/docs/ffs/**'

Psycho | 精神科:
- changed-files:
  - any-glob-to-any-file:
    - '**/docs/psyco/**'
    - '**/docs/psycho/**'

Voice | 声音相关:
- changed-files:
  - any-glob-to-any-file:
    - '**/docs/docs/vocal-surgery/**'
    - '**/docs/docs/vocal-therapy/**'

Site | 站点:
- changed-files:
  - any-glob-to-any-file: '**/themes/**'
