name: 报告新的 HRT 医生
description: 报告新的 HRT 医生
labels: [HRT]
body:
  - type: markdown
    attributes:
      value: 感谢您的报告，请根据该表单填充必要信息。
  - type: input
    id: hospital-name
    attributes:
      label: 医院名称
      description: 该医院的名字全称
    validations:
      required: true
  - type: input
    id: doctor-name
    attributes:
      label: 医生姓名
      description: 该医生的名字
    validations:
      required: true
  - type: dropdown
    id: labels
    attributes:
      label: 标签
      multiple: true
      options:
        - 提供 HRT 指导
        - 需家长同意
        - 有检查项目
  - type: dropdown
    id: drugs
    attributes:
      label: 可开具的药品
      description: 请在注意事项中特别指明药品的「商品名」
      multiple: true
      options:
        - 戊酸雌二醇
        - 苯甲酸雌二醇
        - 雌二醇水合物
        - 醋酸环丙孕酮
        - 螺内酯
        - 比卡鲁胺
        - 其他
    validations:
      required: true
  - type: textarea
    id: caveats
    attributes:
      label: 注意事项
      description: 您在面诊时遭遇的问题以及一些问诊细节
    validations:
      required: true
  - type: checkboxes
    id: license
    attributes:
      label: 以 CC-BY-SA 4.0 协议分发
      description: 本站采用 [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.zh-Hans) 协议分发内容
      options:
        - label: 我同意以 CC-BY-SA 4.0 协议分发
          required: true
